name: push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  test-cover-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Build and test with integration coverage
        run: |
          go build -cover -v
          mkdir -p coverage
          GOCOVERDIR="$(pwd)/coverage" go test ./... -v -count=1
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-integration
          path: coverage
  test-cover-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Build and test with unit coverage
        run: |
          go build -v
          mkdir -p coverage
          go test ./... -v -count=1 -cover -args -test.gocoverdir="$PWD/coverage"
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-unit
          path: coverage
  coverage:
    runs-on: ubuntu-latest
    needs: [test-cover-integration, test-cover-build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
      - name: Process coverage
        run: |
          go tool covdata textfmt -i=./coverage-integration,./coverage-unit -o=coverage.txt
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
