name: build-linux

on:
  workflow_call:
    inputs:
      tag:
        description: "Tag to checkout and build"
        type: string
        required: true
      version:
        description: "Version without the leading 'v'"
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: '${{ inputs.tag }}'
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: ruby/setup-ruby@v1.146.0
        with:
          ruby-version: '3.1'
      - run: gem install fpm
      - run: |
          mkdir -p build/usr/bin
          GOARCH=${{ matrix.arch }} GOOS=${{ matrix.os }} go build -o build/usr/bin/quickhook
          fpm \
            --input-type dir \
            --output-type deb \
            --package quickhook-${{ inputs.version }}-${{ matrix.arch }}.deb \
            --name quickhook \
            --license bsd-3-clause \
            --version ${{ inputs.version }} \
            --architecture ${{ matrix.arch }} \
            --chdir build .
      - uses: actions/upload-artifact@v3
        with:
          name: debs
          path: '*.deb'
