name: build-linux

on:
  workflow_call:
    inputs:
      version:
        description: "Version without the leading 'v'"
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: ruby/setup-ruby@v1.146.0
        with:
          ruby-version: '3.1'
      - run: gem install fpm
      - name: Set version
        run: sed -i "s/VERSION = \"main\"/VERSION = \"${{ inputs.version }}\"/" quickhook.go
      - name: Build
        run: |
          mkdir -p build/usr/bin
          GOARCH=${{ matrix.arch }} GOOS=${{ matrix.os }} CGO_ENABLED=0 go build -o build/usr/bin/quickhook
      - name: Package .debs
        run: |
          fpm \
            --input-type dir \
            --output-type deb \
            --package quickhook-${{ inputs.version }}-${{ matrix.arch }}.deb \
            --name quickhook \
            --license bsd-3-clause \
            --version ${{ inputs.version }} \
            --architecture ${{ matrix.arch }} \
            --chdir build .
      - uses: actions/upload-artifact@v3
        with:
          name: debs
          path: '*.deb'
      - name: Package .rpms
        run: |
          fpm \
            --input-type dir \
            --output-type rpm \
            --package quickhook-${{ inputs.version }}-${{ matrix.arch }}.rpm \
            --name quickhook \
            --license bsd-3-clause \
            --version ${{ inputs.version }} \
            --architecture ${{ matrix.arch }} \
            --chdir build .
      - uses: actions/upload-artifact@v3
        with:
          name: rpms
          path: '*.rpm'
