name: release-verify-rpm-rhel

on:
  workflow_call:
    inputs:
      version:
        description: "Version without the leading 'v'"
        type: string
        required: true

jobs:
  verify:
    runs-on: ubuntu-latest
    container: redhat/ubi8-minimal:latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
      - run: |
          rpm --package quickhook-${{ inputs.version }}-linux-amd64.rpm --query --info
          rpm --package quickhook-${{ inputs.version }}-linux-amd64.rpm --query --list
          rpm --install quickhook-${{ inputs.version }}-linux-amd64.rpm
      - run: |
          quickhook --version
          [[ $(quickhook --version) == "${{ inputs.version }}" ]]
