name: verify-linux-deb

on:
  workflow_call:
    inputs:
      version:
        description: "Version without the leading 'v'"
        type: string
        required: true

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: debs
    - run: |
        dpkg --contents quickhook-${{ inputs.version }}-amd64.deb
        sudo apt install ./quickhook-${{ inputs.version }}-amd64.deb
    - run: |
        quickhook --version
        [[ $(quickhook --version) == "${{ inputs.version }}" ]]
